config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "/contact", to: "static_pages#contact"
  get "/about",   to: "static_pages#about"
  get "/signup", to: "users#new"
  post "signup", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users
  resources :dishes
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]

  def new
  end

  def create
    @user = User.find_by email: params[:password_reset][:email].downcase
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "please check your email to reset password!"
      redirect_to root_url
    else
      flash[:danger] = "email is not valid"
      render "new"
    end
  rescue Net::OpenTimeout
    flash[:danger] = "request timeout!"
    render "new"
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @user.errors.add :password, "can't be empty"
      render "edit"
    elsif @user.update_attributes user_params
      log_in @user
      flash[:success] = "password has beed reset"
      redirect_to @user
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit :password, :password_confirmation
  end

  # Before filters

  def get_user
    @user = User.find_by email: params[:email]
  end

  # Confirms a valid user.
  def valid_user
    return if @user && @user.activated? &&
      @user.authenticated?(:reset, params[:id])
    redirect_to root_url
  end

  # Checks expiration of reset token.
  def check_expiration
    return unless @user.password_reset_expired?
    flash[:danger] = "Password reset has expired."
    redirect_to new_password_reset_url
  end
end

app/views/password_resets/edit.html.erb
<% provide :title, t(".reset_password") %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for @user, url: password_reset_path(params[:id]) do |f| %>
      <%#= render "shared/error_messages" %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

      <%= f.submit "Update password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide :title, t(".forgot_password") %>
<% provide :button_text, t(".send_email") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for :password_reset, url: password_resets_path do |f| %>
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control", value: "nvt94.ptit@gmail.com" %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>