config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "/contact", to: "static_pages#contact"
  get "/about",   to: "static_pages#about"
  get "/signup", to: "users#new"
  post "signup", to: "users#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"

  resources :users
  resources :dishes
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="bg1">
  <div class="container p-t-40 p-b-70">
    <div class="row">
      <div class="col-sm-6 col-md-4 p-t-50">
        <!-- - -->
        <h4 class="txt13 m-b-33">
          <%= t ".contact_us" %>
        </h4>

        <ul class="m-b-70">
          <li class="txt14 m-b-14">
            <i class="fa fa-map-marker fs-16 dis-inline-block size19" aria-hidden="true"></i>
            <%= t ".address" %>
          </li>

          <li class="txt14 m-b-14">
            <i class="fa fa-phone fs-16 dis-inline-block size19" aria-hidden="true"></i>
            (+1) 96 716 6879
          </li>

          <li class="txt14 m-b-14">
            <i class="fa fa-envelope fs-13 dis-inline-block size19" aria-hidden="true"></i>
            contact@site.com
          </li>
        </ul>

        <!-- - -->
        <h4 class="txt13 m-b-32">
          <%= t ".opening_time" %>
        </h4>

        <ul>
          <li class="txt14">
            09:30 AM – 11:00 PM
          </li>

          <li class="txt14">
            <%= t ".every_day" %>
          </li>
        </ul>
      </div>

      <div class="col-sm-6 col-md-4 p-t-50">
        <!-- - -->
        <h4 class="txt13 m-b-33">
          Latest twitter
        </h4>

        <div class="m-b-25">
          <span class="fs-13 color2 m-r-5">
            <i class="fa fa-twitter" aria-hidden="true"></i>
          </span>
          <a href="#" class="txt15">
            @colorlib
          </a>

          <p class="txt14 m-b-18">
            Activello is a good option. It has a slider built into that displays the featured image in the slider.
            <a href="#" class="txt15">
              https://buff.ly/2zaSfAQ
            </a>
          </p>

          <span class="txt16">
            21 Dec 2017
          </span>
        </div>

        <div>
          <span class="fs-13 color2 m-r-5">
            <i class="fa fa-twitter" aria-hidden="true"></i>
          </span>
          <a href="#" class="txt15">
            @colorlib
          </a>

          <p class="txt14 m-b-18">
            Activello is a good option. It has a slider built into that displays
            <a href="#" class="txt15">
              https://buff.ly/2zaSfAQ
            </a>
          </p>

          <span class="txt16">
            21 Dec 2017
          </span>
        </div>
      </div>

      <div class="col-sm-6 col-md-4 p-t-50">
        <!-- - -->
        <h4 class="txt13 m-b-38">
          <%= t ".gallery" %>
        </h4>

        <!-- Gallery footer -->
        <div class="wrap-gallery-footer flex-w">
<!--          <a class="item-gallery-footer wrap-pic-w" href="images/photo-gallery-01.jpg" data-lightbox="gallery-footer">-->
<!--            <img src="images/photo-gallery-thumb-01.jpg" alt="GALLERY">-->
<!--          </a> -->
        </div>

      </div>
    </div>
  </div>

  <div class="end-footer bg2">
    <div class="container">
      <div class="flex-sb-m flex-w p-t-22 p-b-22">
        <div class="p-t-5 p-b-5">
          <a href="#" class="fs-15 c-white"><i class="fa fa-google" aria-hidden="true"></i></a>
          <a href="#" class="fs-15 c-white"><i class="fa fa-facebook m-l-18" aria-hidden="true"></i></a>
          <a href="#" class="fs-15 c-white"><i class="fa fa-twitter m-l-18" aria-hidden="true"></i></a>
        </div>

        <div class="txt17 p-r-20 p-t-5 p-b-5">
          Copyright &copy; 2018 All rights reserved  |  This template is made with <i class="fa fa-heart"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="wrap-menu-header gradient1 trans-0-4">
    <div class="container h-full">
      <div class="wrap_header trans-0-3">
        <div class="logo">
          <a href="index.html">
            <img src="<%= image_path "icons/logo.png" %>" alt="IMG-LOGO" data-logofixed="<%= image_path "icons/logo2.png" %>">
          </a>
        </div>
        <div class="wrap_menu p-l-45 p-l-0-xl">
          <nav class="menu">
            <ul class="main_menu">
              <li><%= link_to "Home",         root_path %></li>
              <li><%= link_to "Menu",         "#" %></li>
              <li><%= link_to "Reservation",  "#" %></li>
              <li><%= link_to "Gallery",      "#" %></li>
              <li><%= link_to "About",        about_path %></li>
              <li><%= link_to "Blog",         "#" %></li>
              <li><%= link_to "Contact",      contact_path %></li>
            </ul>
          </nav>
        </div>

        <div class="social flex-w flex-l-m p-r-20">
          <%= link_to content_tag(:i, nil, class: "fa fa-google"), "#" %>
          <%= link_to content_tag(:i, nil, class: "fa fa-facebook m-l-21"), "#" %>
          <%= link_to content_tag(:i, nil, class: "fa fa-twitter m-l-21"), "#" %>

          <button class="btn-show-sidebar m-l-33 trans-0-4"></button>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<aside class="sidebar trans-0-4">
  <!-- Button Hide sidebar -->
  <button class="btn-hide-sidebar ti-close color0-hov trans-0-4"></button>

  <!-- - -->
  <ul class="menu-sidebar p-t-95 p-b-70">
    <li class="t-center m-b-13">
      <a href="index.html" class="txt19">Home</a>
    </li>

    <li class="t-center m-b-13">
      <a href="menu.html" class="txt19">Menu</a>
    </li>

    <li class="t-center m-b-13">
      <a href="gallery.html" class="txt19">Gallery</a>
    </li>

    <li class="t-center m-b-13">
      <a href="about.html" class="txt19">About</a>
    </li>

    <li class="t-center m-b-13">
      <a href="blog.html" class="txt19">Blog</a>
    </li>

    <li class="t-center m-b-33">
      <a href="contact.html" class="txt19">Contact</a>
    </li>

    <li class="t-center">
      <!-- Button3 -->
      <a href="reservation.html" class="btn3 flex-c-m size13 txt11 trans-0-4 m-l-r-auto">
        <%= t ".reservation" %>
      </a>
    </li>
  </ul>

  <!-- - -->
  <div class="gallery-sidebar t-center p-l-60 p-r-60 p-b-40">
    <!-- - -->
    <h4 class="txt20 m-b-33">
      Gallery
    </h4>

    <!-- Gallery -->
    <div class="wrap-gallery-sidebar flex-w">
<!--      <a class="item-gallery-sidebar wrap-pic-w" href="images/photo-gallery-01.jpg" data-lightbox="gallery-footer">-->
<!--        <img src="images/photo-gallery-thumb-01.jpg" alt="GALLERY">-->
<!--      </a> -->
    </div>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => "reload" %>

  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/sidebar" %>

    <!-- Title Page -->
    <%= raise_image_title yield(:title) %>
    <div>
      <% flash.each do |message_type, message| %>
        <%= content_tag :div, message, class: "alert alert-#{message_type}" %>
      <% end %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>